version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
      - ethereum
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:http://host.docker.internal:8545'
      RUST_LOG: info
      GRAPH_LOG: trace
      ETHEREUM_REORG_THRESHOLD: 0
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - '5001:5001'
      - '9090:9090'
    environment:
      IPFS_PATH: /tmp
  ethereum:
    image: thorax/erigon
    ports:
      - '8545:8545'
      - '8546:8546'
    command:
      [
        '--http',
        '--http.addr',
        '0.0.0.0',
        '--http.port',
        '8545',
        '--http.api',
        'eth,net,web3,engine,admin,erigon,debug,trace,txpool',
        '--http.vhosts',
        '*',
        '--http.corsdomain',
        '*',
        '--datadir',
        'dev',
        '--chain',
        'dev',
        '--private.api.addr',
        '0.0.0.0:9090',
        '--mine',
        '--ws',
      ]
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command:
      [
        'postgres',
        '-cshared_preload_libraries=pg_stat_statements',
        '-cmax_connections=200',
      ]
    environment:
      POSTGRES_MULTIPLE_DATABASES: 'graph-node,explorer'
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      PGDATA: /tmp
  explorer:
    image: alethio/ethereum-lite-explorer
    ports:
      - '4000:80'
    environment:
      APP_NODE_URL: http://localhost:8545
