version: '3'
services:
  graph-node:
    depends_on:
      - ethereum
    environment:
      ethereum: 'mainnet:ethereum:8545'
  ethereum:
    image: thorax/erigon
    ports:
      - '8545:8545'
      - '8546:8546'
    command:
      [
        '--http',
        '--http.addr',
        '0.0.0.0',
        '--http.port',
        '8545',
        '--http.api',
        'eth,net,web3,engine,admin,erigon,debug,trace,txpool',
        '--http.vhosts',
        '*',
        '--http.corsdomain',
        '*',
        '--datadir',
        'dev',
        '--chain',
        'dev',
        '--private.api.addr',
        '0.0.0.0:9090',
        '--mine',
        '--ws',
      ]
  explorer:
    image: alethio/ethereum-lite-explorer
    ports:
      - '4000:80'
    environment:
      APP_NODE_URL: http://localhost:8545
