version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:https://galileo.web3q.io:8545'
      RUST_LOG: info
      GRAPH_LOG: debug
      ETHEREUM_REORG_THRESHOLD: 0
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - '5001:5001'
      - '9090:9090'
    environment:
      IPFS_PATH: /tmp
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: 'postgres'
    environment:
      POSTGRES_MULTIPLE_DATABASES: 'graph-node,explorer'
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      PGDATA: /tmp
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
